# Generated by Django 4.1.7 on 2023-03-28 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sport', models.CharField(blank=True, choices=[('carrom', 'carrom'), ('chess', 'chess'), ('cricket', 'cricket')], max_length=20, null=True)),
                ('playing_position', models.CharField(blank=True, choices=[('winner', 'winner'), ('runner up', 'runner up')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('senior', 'senior'), ('junior', 'junior'), ('sub junior', 'sub junior')], max_length=20, null=True)),
                ('level', models.CharField(blank=True, choices=[('national', 'national'), ('international', 'international')], max_length=50, null=True)),
                ('is_ews', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=20, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=256, null=True)),
                ('mobile_number', models.BigIntegerField(blank=True, null=True)),
                ('aadhar_number', models.BigIntegerField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, choices=[('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Pondicherry', 'Pondicherry'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=50, null=True)),
                ('pin_code', models.BigIntegerField(blank=True, null=True)),
                ('educational_details', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/photo')),
                ('sign', models.FileField(blank=True, null=True, upload_to='documents/sign')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='documents/birth-cert')),
                ('aadhar', models.FileField(blank=True, null=True, upload_to='documents/aadhar')),
                ('pan', models.FileField(blank=True, null=True, upload_to='documents/pan')),
                ('passport', models.FileField(blank=True, null=True, upload_to='documents/passport')),
                ('other_achievements', models.TextField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Scholars',
                'verbose_name_plural': 'Scholars',
            },
        ),
        migrations.CreateModel(
            name='SportsAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(blank=True, max_length=256, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('achievement', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('national', 'national'), ('international', 'international')], max_length=50, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='SportCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates')),
                ('scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.scholarship')),
            ],
        ),
    ]
