# Generated by Django 4.1.7 on 2023-03-29 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportcertificates',
            name='scholar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_cert', to='home.scholarship'),
        ),
        migrations.AlterField(
            model_name='sportsachievements',
            name='scholar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ach', to='home.scholarship'),
        ),
    ]
