# Generated by Django 4.1.7 on 2023-03-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sportcertificates_scholar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsachievements',
            name='awards',
        ),
    ]
