# Generated by Django 4.1.7 on 2023-04-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_sportsachievements_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='declare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='tnc',
            field=models.BooleanField(default=False),
        ),
    ]
