# Generated by Django 4.1.7 on 2023-04-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_scholarship_declare_scholarship_tnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='OtherDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/photo')),
                ('sign', models.FileField(blank=True, null=True, upload_to='documents/sign')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='documents/birth-cert')),
                ('aadhar', models.FileField(blank=True, null=True, upload_to='documents/aadhar')),
                ('pan', models.FileField(blank=True, null=True, upload_to='documents/pan')),
                ('passport', models.FileField(blank=True, null=True, upload_to='documents/passport')),
                ('scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_other', to='home.scholarship')),
            ],
        ),
    ]
