# Generated by Django 4.1.7 on 2023-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_scholarship_aadhar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
